// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.WebMVC.App.Models;

namespace DMMS.WebApp.Services
{
    public class CategoryService : Interfaces.ICategoryService
    {
        private readonly DMMSWebMVCAppContext _db;
        public CategoryService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<Category>> GetAllAsync() => await _db.Set<Category>().AsNoTracking().ToListAsync();
        public async Task<Category?> GetByIdAsync(int id) => await _db.Set<Category>().FindAsync(id);

        public async Task<Category> CreateAsync(Category entity)
        {
            _db.Set<Category>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, Category entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}