// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class CMSTypeService : Interfaces.ICMSTypeService
    {
        private readonly DMMSWebMVCAppContext _db;
        public CMSTypeService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<CMSType>> GetAllAsync() => await _db.Set<CMSType>().AsNoTracking().ToListAsync();
        public async Task<CMSType?> GetByIdAsync(int id) => await _db.Set<CMSType>().FindAsync(id);

        public async Task<CMSType> CreateAsync(CMSType entity)
        {
            _db.Set<CMSType>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, CMSType entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}