// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class CompanyService : Interfaces.ICompanyService
    {
        private readonly DMMSWebMVCAppContext _db;
        public CompanyService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<Company>> GetAllAsync() => await _db.Set<Company>().AsNoTracking().ToListAsync();
        public async Task<Company?> GetByIdAsync(int id) => await _db.Set<Company>().FindAsync(id);

        public async Task<Company> CreateAsync(Company entity)
        {
            _db.Set<Company>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, Company entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}