// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentEditedService : Interfaces.IContentEditedService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentEditedService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentEdited>> GetAllAsync() => await _db.Set<ContentEdited>().AsNoTracking().ToListAsync();
        public async Task<ContentEdited?> GetByIdAsync(int id) => await _db.Set<ContentEdited>().FindAsync(id);

        public async Task<ContentEdited> CreateAsync(ContentEdited entity)
        {
            _db.Set<ContentEdited>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentEdited entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}