// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentLinksReferenceService : Interfaces.IContentLinksReferenceService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentLinksReferenceService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentLinksReference>> GetAllAsync() => await _db.Set<ContentLinksReference>().AsNoTracking().ToListAsync();
        public async Task<ContentLinksReference?> GetByIdAsync(int id) => await _db.Set<ContentLinksReference>().FindAsync(id);

        public async Task<ContentLinksReference> CreateAsync(ContentLinksReference entity)
        {
            _db.Set<ContentLinksReference>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentLinksReference entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}