// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentLinksSocialService : Interfaces.IContentLinksSocialService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentLinksSocialService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentLinksSocial>> GetAllAsync() => await _db.Set<ContentLinksSocial>().AsNoTracking().ToListAsync();
        public async Task<ContentLinksSocial?> GetByIdAsync(int id) => await _db.Set<ContentLinksSocial>().FindAsync(id);

        public async Task<ContentLinksSocial> CreateAsync(ContentLinksSocial entity)
        {
            _db.Set<ContentLinksSocial>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentLinksSocial entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}