// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentCodedService : Interfaces.IContentCodedService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentCodedService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentCoded>> GetAllAsync() => await _db.Set<ContentCoded>().AsNoTracking().ToListAsync();
        public async Task<ContentCoded?> GetByIdAsync(int id) => await _db.Set<ContentCoded>().FindAsync(id);

        public async Task<ContentCoded> CreateAsync(ContentCoded entity)
        {
            _db.Set<ContentCoded>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentCoded entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}