// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentSectionService : Interfaces.IContentSectionService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentSectionService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentSection>> GetAllAsync() => await _db.Set<ContentSection>().AsNoTracking().ToListAsync();
        public async Task<ContentSection?> GetByIdAsync(int id) => await _db.Set<ContentSection>().FindAsync(id);

        public async Task<ContentSection> CreateAsync(ContentSection entity)
        {
            _db.Set<ContentSection>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentSection entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}