// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentLinksAffiliateService : Interfaces.IContentLinksAffiliateService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentLinksAffiliateService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentLinksAffiliate>> GetAllAsync() => await _db.Set<ContentLinksAffiliate>().AsNoTracking().ToListAsync();
        public async Task<ContentLinksAffiliate?> GetByIdAsync(int id) => await _db.Set<ContentLinksAffiliate>().FindAsync(id);

        public async Task<ContentLinksAffiliate> CreateAsync(ContentLinksAffiliate entity)
        {
            _db.Set<ContentLinksAffiliate>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentLinksAffiliate entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}