// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentResultService : Interfaces.IContentResultService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentResultService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentResult>> GetAllAsync() => await _db.Set<ContentResult>().AsNoTracking().ToListAsync();
        public async Task<ContentResult?> GetByIdAsync(int id) => await _db.Set<ContentResult>().FindAsync(id);

        public async Task<ContentResult> CreateAsync(ContentResult entity)
        {
            _db.Set<ContentResult>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentResult entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}