// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentTypeService : Interfaces.IContentTypeService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentTypeService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentType>> GetAllAsync() => await _db.Set<ContentType>().AsNoTracking().ToListAsync();
        public async Task<ContentType?> GetByIdAsync(int id) => await _db.Set<ContentType>().FindAsync(id);

        public async Task<ContentType> CreateAsync(ContentType entity)
        {
            _db.Set<ContentType>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentType entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}