// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentSocialService : Interfaces.IContentSocialService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentSocialService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentSocial>> GetAllAsync() => await _db.Set<ContentSocial>().AsNoTracking().ToListAsync();
        public async Task<ContentSocial?> GetByIdAsync(int id) => await _db.Set<ContentSocial>().FindAsync(id);

        public async Task<ContentSocial> CreateAsync(ContentSocial entity)
        {
            _db.Set<ContentSocial>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentSocial entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}