// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentGeneratedService : Interfaces.IContentGeneratedService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentGeneratedService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentGenerated>> GetAllAsync() => await _db.Set<ContentGenerated>().AsNoTracking().ToListAsync();
        public async Task<ContentGenerated?> GetByIdAsync(int id) => await _db.Set<ContentGenerated>().FindAsync(id);

        public async Task<ContentGenerated> CreateAsync(ContentGenerated entity)
        {
            _db.Set<ContentGenerated>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentGenerated entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}