// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentRawService : Interfaces.IContentRawService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentRawService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentRaw>> GetAllAsync() => await _db.Set<ContentRaw>().AsNoTracking().ToListAsync();
        public async Task<ContentRaw?> GetByIdAsync(int id) => await _db.Set<ContentRaw>().FindAsync(id);

        public async Task<ContentRaw> CreateAsync(ContentRaw entity)
        {
            _db.Set<ContentRaw>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentRaw entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}