// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentService : Interfaces.IContentService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<Content>> GetAllAsync() => await _db.Set<Content>().AsNoTracking().ToListAsync();
        public async Task<Content?> GetByIdAsync(int id) => await _db.Set<Content>().FindAsync(id);

        public async Task<Content> CreateAsync(Content entity)
        {
            _db.Set<Content>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, Content entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}