// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentLinksMediaService : Interfaces.IContentLinksMediaService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentLinksMediaService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentLinksMedia>> GetAllAsync() => await _db.Set<ContentLinksMedia>().AsNoTracking().ToListAsync();
        public async Task<ContentLinksMedia?> GetByIdAsync(int id) => await _db.Set<ContentLinksMedia>().FindAsync(id);

        public async Task<ContentLinksMedia> CreateAsync(ContentLinksMedia entity)
        {
            _db.Set<ContentLinksMedia>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentLinksMedia entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}