// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class ContentLinksBackLinksService : Interfaces.IContentLinksBackLinksService
    {
        private readonly DMMSWebMVCAppContext _db;
        public ContentLinksBackLinksService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<ContentLinksBackLinks>> GetAllAsync() => await _db.Set<ContentLinksBackLinks>().AsNoTracking().ToListAsync();
        public async Task<ContentLinksBackLinks?> GetByIdAsync(int id) => await _db.Set<ContentLinksBackLinks>().FindAsync(id);

        public async Task<ContentLinksBackLinks> CreateAsync(ContentLinksBackLinks entity)
        {
            _db.Set<ContentLinksBackLinks>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, ContentLinksBackLinks entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}