// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class EnvironmentService : Interfaces.IEnvironmentService
    {
        private readonly DMMSWebMVCAppContext _db;
        public EnvironmentService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<Environment>> GetAllAsync() => await _db.Set<Environment>().AsNoTracking().ToListAsync();
        public async Task<Environment?> GetByIdAsync(int id) => await _db.Set<Environment>().FindAsync(id);

        public async Task<Environment> CreateAsync(Environment entity)
        {
            _db.Set<Environment>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, Environment entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}