// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class KeywordProviderService : Interfaces.IKeywordProviderService
    {
        private readonly DMMSWebMVCAppContext _db;
        public KeywordProviderService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<KeywordProvider>> GetAllAsync() => await _db.Set<KeywordProvider>().AsNoTracking().ToListAsync();
        public async Task<KeywordProvider?> GetByIdAsync(int id) => await _db.Set<KeywordProvider>().FindAsync(id);

        public async Task<KeywordProvider> CreateAsync(KeywordProvider entity)
        {
            _db.Set<KeywordProvider>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, KeywordProvider entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}