// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class KeywordService : Interfaces.IKeywordService
    {
        private readonly DMMSWebMVCAppContext _db;
        public KeywordService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<Keyword>> GetAllAsync() => await _db.Set<Keyword>().AsNoTracking().ToListAsync();
        public async Task<Keyword?> GetByIdAsync(int id) => await _db.Set<Keyword>().FindAsync(id);

        public async Task<Keyword> CreateAsync(Keyword entity)
        {
            _db.Set<Keyword>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, Keyword entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}