// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class KeywordMapService : Interfaces.IKeywordMapService
    {
        private readonly DMMSWebMVCAppContext _db;
        public KeywordMapService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<KeywordMap>> GetAllAsync() => await _db.Set<KeywordMap>().AsNoTracking().ToListAsync();
        public async Task<KeywordMap?> GetByIdAsync(int id) => await _db.Set<KeywordMap>().FindAsync(id);

        public async Task<KeywordMap> CreateAsync(KeywordMap entity)
        {
            _db.Set<KeywordMap>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, KeywordMap entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}