// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class PublisherService : Interfaces.IPublisherService
    {
        private readonly DMMSWebMVCAppContext _db;
        public PublisherService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<Publisher>> GetAllAsync() => await _db.Set<Publisher>().AsNoTracking().ToListAsync();
        public async Task<Publisher?> GetByIdAsync(int id) => await _db.Set<Publisher>().FindAsync(id);

        public async Task<Publisher> CreateAsync(Publisher entity)
        {
            _db.Set<Publisher>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, Publisher entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}