// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class SellerEntityService : Interfaces.ISellerEntityService
    {
        private readonly DMMSWebMVCAppContext _db;
        public SellerEntityService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<SellerEntity>> GetAllAsync() => await _db.Set<SellerEntity>().AsNoTracking().ToListAsync();
        public async Task<SellerEntity?> GetByIdAsync(int id) => await _db.Set<SellerEntity>().FindAsync(id);

        public async Task<SellerEntity> CreateAsync(SellerEntity entity)
        {
            _db.Set<SellerEntity>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, SellerEntity entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}