// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class SocialMediaTypeService : Interfaces.ISocialMediaTypeService
    {
        private readonly DMMSWebMVCAppContext _db;
        public SocialMediaTypeService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<SocialMediaType>> GetAllAsync() => await _db.Set<SocialMediaType>().AsNoTracking().ToListAsync();
        public async Task<SocialMediaType?> GetByIdAsync(int id) => await _db.Set<SocialMediaType>().FindAsync(id);

        public async Task<SocialMediaType> CreateAsync(SocialMediaType entity)
        {
            _db.Set<SocialMediaType>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, SocialMediaType entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}