// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class TagService : Interfaces.ITagService
    {
        private readonly DMMSWebMVCAppContext _db;
        public TagService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<Tag>> GetAllAsync() => await _db.Set<Tag>().AsNoTracking().ToListAsync();
        public async Task<Tag?> GetByIdAsync(int id) => await _db.Set<Tag>().FindAsync(id);

        public async Task<Tag> CreateAsync(Tag entity)
        {
            _db.Set<Tag>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, Tag entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}