// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class UserService : Interfaces.IUserService
    {
        private readonly DMMSWebMVCAppContext _db;
        public UserService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<User>> GetAllAsync() => await _db.Set<User>().AsNoTracking().ToListAsync();
        public async Task<User?> GetByIdAsync(int id) => await _db.Set<User>().FindAsync(id);

        public async Task<User> CreateAsync(User entity)
        {
            _db.Set<User>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, User entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}