// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DMMS.WebMVC.App.Data;
using DMMS.Models;

namespace DMMS.WebApp.Services
{
    public class WebsiteTypeService : Interfaces.IWebsiteTypeService
    {
        private readonly DMMSWebMVCAppContext _db;
        public WebsiteTypeService(DMMSWebMVCAppContext db)
        {
            _db = db;
        }

        public async Task<List<WebsiteType>> GetAllAsync() => await _db.Set<WebsiteType>().AsNoTracking().ToListAsync();
        public async Task<WebsiteType?> GetByIdAsync(int id) => await _db.Set<WebsiteType>().FindAsync(id);

        public async Task<WebsiteType> CreateAsync(WebsiteType entity)
        {
            _db.Set<WebsiteType>().Add(entity);
            await _db.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> UpdateAsync(int id, WebsiteType entity)
        {
            _db.Entry(entity).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var existing = await GetByIdAsync(id);
            if (existing == null) return false;
            _db.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}