// <auto-generated />
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DMMS.WebApp.Services.Interfaces;
using DMMS.Models;

namespace DMMS.WebApp.Controllers
{
    public class CMSTypeController : Controller
    {
        private readonly ICMSTypeService _service;
        public CMSTypeController(ICMSTypeService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var items = await _service.GetAllAsync();
            return View(items);
        }

        public async Task<IActionResult> Details(int id)
        {
            var item = await _service.GetByIdAsync(id);
            if (item == null) return NotFound();
            return View(item);
        }

        //public IActionResult Create() => View(new CMSType());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CMSType model)
        {
            if (!ModelState.IsValid) return View(model);
            await _service.CreateAsync(model);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var item = await _service.GetByIdAsync(id);
            if (item == null) return NotFound();
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CMSType model)
        {
            if (!ModelState.IsValid) return View(model);
            var ok = await _service.UpdateAsync(id, model);
            if (!ok) return NotFound();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var item = await _service.GetByIdAsync(id);
            if (item == null) return NotFound();
            return View(item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}