// <auto-generated />
using Microsoft.Extensions.DependencyInjection;

namespace DMMS.WebApp.Infrastructure
{
    public static class DependencyInjection
    {
        public static IServiceCollection AddGeneratedServices(this IServiceCollection services)
        {
    services.AddScoped<{ns}.Interfaces.{ifaceName}, {ns}.{svcName}>();
            return services;
        }
    }
}