// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.WebMVC.App.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface ICategoryService
    {
        Task<List<Category>> GetAllAsync();
        Task<Category?> GetByIdAsync(int id);
        Task<Category> CreateAsync(Category entity);
        Task<bool> UpdateAsync(int id, Category entity);
        Task<bool> DeleteAsync(int id);
    }
}