// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface ICMSTypeService
    {
        Task<List<CMSType>> GetAllAsync();
        Task<CMSType?> GetByIdAsync(int id);
        Task<CMSType> CreateAsync(CMSType entity);
        Task<bool> UpdateAsync(int id, CMSType entity);
        Task<bool> DeleteAsync(int id);
    }
}