// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentLinksReferenceService
    {
        Task<List<ContentLinksReference>> GetAllAsync();
        Task<ContentLinksReference?> GetByIdAsync(int id);
        Task<ContentLinksReference> CreateAsync(ContentLinksReference entity);
        Task<bool> UpdateAsync(int id, ContentLinksReference entity);
        Task<bool> DeleteAsync(int id);
    }
}