// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentSocialService
    {
        Task<List<ContentSocial>> GetAllAsync();
        Task<ContentSocial?> GetByIdAsync(int id);
        Task<ContentSocial> CreateAsync(ContentSocial entity);
        Task<bool> UpdateAsync(int id, ContentSocial entity);
        Task<bool> DeleteAsync(int id);
    }
}