// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentLinksAffiliateService
    {
        Task<List<ContentLinksAffiliate>> GetAllAsync();
        Task<ContentLinksAffiliate?> GetByIdAsync(int id);
        Task<ContentLinksAffiliate> CreateAsync(ContentLinksAffiliate entity);
        Task<bool> UpdateAsync(int id, ContentLinksAffiliate entity);
        Task<bool> DeleteAsync(int id);
    }
}