// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentResultService
    {
        Task<List<ContentResult>> GetAllAsync();
        Task<ContentResult?> GetByIdAsync(int id);
        Task<ContentResult> CreateAsync(ContentResult entity);
        Task<bool> UpdateAsync(int id, ContentResult entity);
        Task<bool> DeleteAsync(int id);
    }
}