// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentLinksMediaService
    {
        Task<List<ContentLinksMedia>> GetAllAsync();
        Task<ContentLinksMedia?> GetByIdAsync(int id);
        Task<ContentLinksMedia> CreateAsync(ContentLinksMedia entity);
        Task<bool> UpdateAsync(int id, ContentLinksMedia entity);
        Task<bool> DeleteAsync(int id);
    }
}