// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentCodedService
    {
        Task<List<ContentCoded>> GetAllAsync();
        Task<ContentCoded?> GetByIdAsync(int id);
        Task<ContentCoded> CreateAsync(ContentCoded entity);
        Task<bool> UpdateAsync(int id, ContentCoded entity);
        Task<bool> DeleteAsync(int id);
    }
}