// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentRawService
    {
        Task<List<ContentRaw>> GetAllAsync();
        Task<ContentRaw?> GetByIdAsync(int id);
        Task<ContentRaw> CreateAsync(ContentRaw entity);
        Task<bool> UpdateAsync(int id, ContentRaw entity);
        Task<bool> DeleteAsync(int id);
    }
}