// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentSectionService
    {
        Task<List<ContentSection>> GetAllAsync();
        Task<ContentSection?> GetByIdAsync(int id);
        Task<ContentSection> CreateAsync(ContentSection entity);
        Task<bool> UpdateAsync(int id, ContentSection entity);
        Task<bool> DeleteAsync(int id);
    }
}