// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentLinksBackLinksService
    {
        Task<List<ContentLinksBackLinks>> GetAllAsync();
        Task<ContentLinksBackLinks?> GetByIdAsync(int id);
        Task<ContentLinksBackLinks> CreateAsync(ContentLinksBackLinks entity);
        Task<bool> UpdateAsync(int id, ContentLinksBackLinks entity);
        Task<bool> DeleteAsync(int id);
    }
}