// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentTypeService
    {
        Task<List<ContentType>> GetAllAsync();
        Task<ContentType?> GetByIdAsync(int id);
        Task<ContentType> CreateAsync(ContentType entity);
        Task<bool> UpdateAsync(int id, ContentType entity);
        Task<bool> DeleteAsync(int id);
    }
}