// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentGeneratedService
    {
        Task<List<ContentGenerated>> GetAllAsync();
        Task<ContentGenerated?> GetByIdAsync(int id);
        Task<ContentGenerated> CreateAsync(ContentGenerated entity);
        Task<bool> UpdateAsync(int id, ContentGenerated entity);
        Task<bool> DeleteAsync(int id);
    }
}