// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentLinksSocialService
    {
        Task<List<ContentLinksSocial>> GetAllAsync();
        Task<ContentLinksSocial?> GetByIdAsync(int id);
        Task<ContentLinksSocial> CreateAsync(ContentLinksSocial entity);
        Task<bool> UpdateAsync(int id, ContentLinksSocial entity);
        Task<bool> DeleteAsync(int id);
    }
}