// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentService
    {
        Task<List<Content>> GetAllAsync();
        Task<Content?> GetByIdAsync(int id);
        Task<Content> CreateAsync(Content entity);
        Task<bool> UpdateAsync(int id, Content entity);
        Task<bool> DeleteAsync(int id);
    }
}