// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IContentEditedService
    {
        Task<List<ContentEdited>> GetAllAsync();
        Task<ContentEdited?> GetByIdAsync(int id);
        Task<ContentEdited> CreateAsync(ContentEdited entity);
        Task<bool> UpdateAsync(int id, ContentEdited entity);
        Task<bool> DeleteAsync(int id);
    }
}