// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IEnvironmentService
    {
        Task<List<Environment>> GetAllAsync();
        Task<Environment?> GetByIdAsync(int id);
        Task<Environment> CreateAsync(Environment entity);
        Task<bool> UpdateAsync(int id, Environment entity);
        Task<bool> DeleteAsync(int id);
    }
}