// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IKeywordProviderService
    {
        Task<List<KeywordProvider>> GetAllAsync();
        Task<KeywordProvider?> GetByIdAsync(int id);
        Task<KeywordProvider> CreateAsync(KeywordProvider entity);
        Task<bool> UpdateAsync(int id, KeywordProvider entity);
        Task<bool> DeleteAsync(int id);
    }
}