// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IKeywordMapService
    {
        Task<List<KeywordMap>> GetAllAsync();
        Task<KeywordMap?> GetByIdAsync(int id);
        Task<KeywordMap> CreateAsync(KeywordMap entity);
        Task<bool> UpdateAsync(int id, KeywordMap entity);
        Task<bool> DeleteAsync(int id);
    }
}