// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IKeywordService
    {
        Task<List<Keyword>> GetAllAsync();
        Task<Keyword?> GetByIdAsync(int id);
        Task<Keyword> CreateAsync(Keyword entity);
        Task<bool> UpdateAsync(int id, Keyword entity);
        Task<bool> DeleteAsync(int id);
    }
}