// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IKeywordTopicService
    {
        Task<List<KeywordTopic>> GetAllAsync();
        Task<KeywordTopic?> GetByIdAsync(int id);
        Task<KeywordTopic> CreateAsync(KeywordTopic entity);
        Task<bool> UpdateAsync(int id, KeywordTopic entity);
        Task<bool> DeleteAsync(int id);
    }
}