// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface INicheService
    {
        Task<List<Niche>> GetAllAsync();
        Task<Niche?> GetByIdAsync(int id);
        Task<Niche> CreateAsync(Niche entity);
        Task<bool> UpdateAsync(int id, Niche entity);
        Task<bool> DeleteAsync(int id);
    }
}