// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface ISellerEntityService
    {
        Task<List<SellerEntity>> GetAllAsync();
        Task<SellerEntity?> GetByIdAsync(int id);
        Task<SellerEntity> CreateAsync(SellerEntity entity);
        Task<bool> UpdateAsync(int id, SellerEntity entity);
        Task<bool> DeleteAsync(int id);
    }
}