// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface ISocialMediaTypeService
    {
        Task<List<SocialMediaType>> GetAllAsync();
        Task<SocialMediaType?> GetByIdAsync(int id);
        Task<SocialMediaType> CreateAsync(SocialMediaType entity);
        Task<bool> UpdateAsync(int id, SocialMediaType entity);
        Task<bool> DeleteAsync(int id);
    }
}