// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using DMMS.Models;

namespace DMMS.WebApp.Services.Interfaces
{
    public interface IWebsiteTypeService
    {
        Task<List<WebsiteType>> GetAllAsync();
        Task<WebsiteType?> GetByIdAsync(int id);
        Task<WebsiteType> CreateAsync(WebsiteType entity);
        Task<bool> UpdateAsync(int id, WebsiteType entity);
        Task<bool> DeleteAsync(int id);
    }
}